site_name: SCI-VCF
nav:
    - Home: index.md
    - About: about.md
    - Installation: installation.md
    - Getting Started: get_started.md
    - Gallery: gallery.md
    - FAQ: faq.md
    - Glossory: glossory.md 
    - Change Log: change_log.md
theme: readthedocs